### ISSUE TITLE
Restore Back to Original Hostname after running Anon mode?

### ISSUE THREAD

**Issue by ghost** [RightToPrivacy/wipri#2]
When restoring the previously used host name it just goes back to the last host not the host name stored in /etc/hosts.

Every time After running Anon mode I have to sudo nano /etc/hostname back to the my original host name. I noticed Problems at each boot because I would try install some software or do updates via the terminal. I would get an error and it would take long because the name would be set to whatever the last name was changed to in anon mode. 

I would have to change it back via sudo nano /etc/hostname or sudo hostnamectl set-hostname "My Hostname".

I tried to set preserve_hostname = true in /etc/hosts and still no fix.

I don't no what I'm doing wrong or how to fix this?

>Im running the install.sh with starting at boot and changed my device (wlp2s0) in wipri.service
	
	(not anon at boot)

>Did have and error  message when installing.
	
	Failed to start wipri.service: Unit wipri.service is not loaded properly: Exec format error.
	See system logs and 'systemctl status wipri.service' for details.
	WiPri has been started/added new identity at each boot

>Also don't know if Macchanger installed is interfering either

**Comment by RightToPrivacy** [comment]
Misread your issue earlier thinking it was an issue on using macchanger (seeing your issue, wipri doesn't use macchanger).

If you are still having problems (with wipri), please paste the output of:

 sudo systemctl status wipri

So I can see what the output is from wipri.

If you decide to combine 2 mac changer programs (really no need really but can't harm you unless you set them to preserve opposite mac addresses!), set macchanger only to 'random' in network manager.

The #1 issue people have is they run a few commands that try to set 2 completely opposite mac addresses at same time.

Wipri enforces static mac address changes (made by wipri).

If you wanted to randomize signal + mac simultaneously you may like something more like wipri -d wlp2s0 -s -r to have it leave out the hostname changes.

You can then add wipri -d wlp2s0 -h to change the hostname at will to a random one before connecting to a new network (since hostname is not picked up until on network)

I'll be making more updates.

Will leave this open for about a week to see if you are still having issues using wipri.

**Comment by RightToPrivacy** [comment]
Final thoughts:  You can rely completely on WiPri (and I do many times on machines especially for static settings) but if you have multiple options at hand, I concede it can't hurt to set randomize in Network Manager as well as in wipri. But this is not at all necessary.

Reasoning: having a backup cannot harm us. Just watch out not to set something that conflicts on a wipri static setting as wipri is designed to ensure the static valid mac chosen stays. Reasoning: You do not want 2 programs to conflict. But 2 separate randomization programs, this is fine at this time.

WiPri enforces all static settings to keep the chosen, valid, randomized mac address set. Even in the case of a hardware firmware crash trying to reset the original mac. Part of the reason it has this is I noticed other mac address changers did not catch firmware crashes and those other mac changers leaked perm mac on crash (WiPri static settings do not leak on firmware crash- they enforce the mac).

The "restore hostname" relies on the previous use of "randomize hostname" as it backs up the original hostname (printed in the -H help flag).

It has been almost 2 weeks and I haven't heard anything on your issue.

As such, I am now Closing this issue. 

Please reopen issue if you experience problems directly related to wipri.

Thank you.

**Comment by ghost** [comment]
Ok sorry for late reply, was in proccess of getting a new system. 
But yeah Im not sure what systemctl status wipri output is/was. I have done a fresh install of my distro since the time of my original post. So I don't have Wipri running currently.

> ***In regards to having the two programs running at the same time and commands that try to set 2 completely opposite mac addresses at same time. I think This was the problem.***

I will look into all this and do some testing/troubleshooting on my next Fresh Install on my New Machine.

Thanks, for all the info.

**Comment by RightToPrivacy** [comment]
Thought maybe you were inactive and moved on to other things.

Anyhow I always recommend static flags for places you are staying in place (especially familiar or at home) - as static flags implement unique, forced valid yet random mac enforcing concept (w/experimenting/testing against sniffers and different NIC hardware) that won't allow firmware or system crash to reset the mac to permanent (no matter what). 

If set to a static flag with the 'boot'/systemd installation, you can still change the mac anytime by restarting wipri with:
sudo systemd restart wipri

And it will set a new static mac for you.

When using the continuously changing addresses at continuously changing times/addresses, it's fine/not conflicting to (optionally) add something else like network manager's randomization (as a (not necessary/optional backup enforcement) setting - to add yet another layer of protection as continuously changing wipri does not use the enforcement concept - as it can conflict with different hardware abilities to change IME).

Wipri uses Linux's random to generate the random mac addresses but keeps to wipri's valid OUI rule.

+ things I came up w/experimenting w/sniffing and tracking.

Wipri has been my solution, hope you find it useful. :)

I will be making new additions for things coming up.

**Comment by RightToPrivacy** [comment]
Making an change in hostname restoration in response to this filed issue.

Before, it saved the hostname directly prior to each change to restore. Now, it saves the *original* hostname,
during first run of wipri. The original machine name should be restored on restore.

Any problems, please let me know.

Hope this helps.
