### ISSUE TITLE
Add more "Installation" how to info for new linux users

### ISSUE THREAD

**Issue by ghost** [RightToPrivacy/wipri#4]
- Download from github or other repository.

$ `git clone https://github.com/RightToPrivacy/wipri.git`

- Go to location of *wipri* folder
- Open wipri folder then right click *"Open in Terminal"* or cd to *wipri* location folder.
	
- Then type this in terminal to install.

	$ `sudo bash install.sh`

**Comment by RightToPrivacy** [comment]
Added a bit more recently in relation to your issue. Plan to add other service file options as you suggested. Thanks for the feedback. :)
