### ISSUE TITLE
When using VPN software, VPN software reports that IPv6 isn't working

### ISSUE THREAD

**Issue by Peter4487** [RightToPrivacy/wipri#5]
Hello,

Thanks for this wonderful repo!
I'm observing this VPN software report that IPv6 isn't working when I've set up wipri with wipri -d [adapter] -P, as well as lots of other settings.

Is this by design (i.e., a known limitation)? Or is it a bug?

**Comment by RightToPrivacy** [comment]
Ah, ipv6: you can fix this easily.

It's simple to allow ipv6 (will change this in next update).

All you need to do is open /usr/bin/wipri in your favorite editor, and place hash marks (#) in front of:

```
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 >/dev/null
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1 >/dev/null
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1 >/dev/null
```

(Estimated around lines 157-159)

Change those lines inside /usr/bin/wipri to look like this (simply adding a # in front of each line):

```
#sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 >/dev/null
#sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1 >/dev/null
#sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1 >/dev/null
```

Placing these hash marks in front of those lines prevent changes to ipv6 (preventing all ipv6 related lines from running at all).

If you installed wipri as a systemd service, you can then reboot your system and on that next boot it will load the changed wipri with ipv6 still enabled.

Let me know if anything isn't clear.

In the next update I will add hashes by default to prevent user ipv6 problems in future.

**Comment by Peter4487** [comment]
Thanks for the quick response! I'll test soon.

**Comment by RightToPrivacy** [comment]
Just pushed edited wipri with additional new flag (-w) to the Gitea onion (Tor hidden git service). I upload things there early. Already has the ipv6 hashed out there as well (to allow users to decide).

You can download using Tor browser here: http://gg6zxtreajiijztyy5g6bt5o6l3qu32nrg7eulyemlhxwwl6enk6ghad.onion/RightToPrivacy/WiPri

Or, to clone with git (if you have Tor installed and running), you can optionally download/clone using:

torify git clone http://gg6zxtreajiijztyy5g6bt5o6l3qu32nrg7eulyemlhxwwl6enk6ghad.onion/RightToPrivacy/WiPri.git

Will be adding these new changes to github later on.

Thanks for filing the issue. Appreciate bringing to my attention.

**Comment by RightToPrivacy** [comment]
Just added to github so I'm going to go ahead and close this since it is solved now.
